# Generated by Django 4.1.2 on 2022-12-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('director', 'director'), ('vendor', 'vendor'), ('manager', 'manager'), ('client', 'client')], default='client', max_length=20),
        ),
    ]
