# Generated by Django 4.1.2 on 2022-11-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0001_initial'),
        ('product', '0002_product_lookbook'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='discount.discount'),
        ),
        migrations.AddField(
            model_name='product',
            name='in_discount',
            field=models.BooleanField(default=False),
        ),
    ]
