# Generated by Django 4.1.2 on 2022-11-29 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='product',
            name='in_discount',
        ),
    ]
