# Generated by Django 4.1.2 on 2022-12-01 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsize',
            name='productsize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitemsize', to='product.size'),
        ),
        migrations.AlterField(
            model_name='wishlistsize',
            name='productsize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlistsize', to='product.size'),
        ),
    ]
