# Generated by Django 4.1.2 on 2022-11-25 19:33

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_lookbook'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('productsize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistsize', to='product.productsize')),
            ],
        ),
        migrations.RemoveField(
            model_name='wishlistitemsize',
            name='productsize',
        ),
        migrations.RemoveField(
            model_name='wishlistitemsize',
            name='wishlistitem',
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='product.product'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WishlistItem',
        ),
        migrations.DeleteModel(
            name='WishlistItemSize',
        ),
        migrations.AddField(
            model_name='wishlistsize',
            name='wishlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlistsize', to='order.wishlist'),
        ),
    ]
