# Generated by Django 4.1.2 on 2022-11-28 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_discount_product_in_discount'),
        ('order', '0002_wishlistsize_remove_wishlistitemsize_productsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsize',
            name='productsize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orderitemsize', to='product.productsize'),
        ),
        migrations.AlterField(
            model_name='wishlistsize',
            name='productsize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wishlistsize', to='product.productsize'),
        ),
    ]
